[package]
name = "trysp_rust_on_psp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psp = { version = "0.3.6" }
drogue-tls = { version = "0.2", default-features=false }
drogue-network = "0.2"
rand = { version = "0.7", default-features=false }
rand_chacha = { version = "0.3", default-features=false }

[profile.release]
lto = true
